---
# kubectl create secret generic gh-oauth-example \
#  --from-literal=client-secret=<value> \
#  --dry-run=client -o json | kubeseal -o yaml | tee ./manifests/secret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gh-oauth-example
spec:
  encryptedData:
    client-secret: AgDDTqj4OegEBdvVmOE60YZ3JW3q48m2ClRpyOQtMwVGjHHT3sadphRFY22CPL3Gm1frAWP9IVFzneCRiZN/40mTnG5iXyixZztTKpHaMMXQgbnzWX+/P74spqddWMq+eL08JfgkR0mh/gibyrQr9C3D0WynZsVHEYvF9Ll3bOnk0Rs9InH6V1DxaahDp9iTpz8niti6+bIh6odeCTZVpGWVEDDOTeHiTH6ji3ECtyesuVKYEl0HDAGl/dMTwJaAxZMG8PjtFrVFlF8CBvAPzm/WMAzLyH6hsEwWQsJ87gVzgG2dXtzq+JWA3+iU9/0WjOxo7H0GkmnNTwvawByMGT9N3TMAHKaSPY0xSlMi0Vy1Ia8qEwaKwQkUVKCcGemz1PXW7+c9ElLD1aIprTF2vtf/7DBlYHz6MZATkCowICRaamdvvePBcZLsSazXW0C+FgMLAuDjW6z+UghmOXmEo7j+97vP2vkT6UaPfHekdzANj7mvS7NgXWAOflAQHl3JJ8qQ0g5yVvg0YHim6Ld0EHWytdCdGjyC08QGfy/4kCR77jR6huSUwWfULmZY6g/UttDen+yoFGszm1Ut4MHK6d0+/WGLbhVwHPDjeg2Yi0Z9kA4LxeoJK+axMfcO3/4nugzALohEzWVviygD/DLTT7a+YwM/n9irle++raCsZ0ZmBnRl/fNs3SlBvTPRo4jBYkQAE+pCglY2meY9vqBagCzNvhTRL4LNGkKbESoQRiPXDYMjMaUGS+0o
  template:
    metadata:
      name: gh-oauth-example
