---
# kubectl create secret generic gh-oauth-example \
#  --from-literal=client-secret=<value> \
#  --dry-run=client -o yaml > secret.yaml
apiVersion: v1
data:
  client-secret: base64 encode <value>
kind: Secret
metadata:
  name: gh-oauth-example
